customSyntax: postcss-scss

extends:
  - stylelint-config-recommended
  - stylelint-config-sass-guidelines
  - stylelint-config-css-modules
  - stylelint-config-prettier

plugins:
  - stylelint-prettier

rules:
  # Enforce camel case CSS classes for CSS modules because camel case
  # properties can be accessed using dot notation. For comparison:
  #   `styles['some-class']` vs `styles.someClass`
  selector-class-pattern:
    - ^[a-z][a-zA-Z0-9]+$
    - message: 'Classes should be camelCase'

  max-nesting-depth:
    - 4
    - ignore:
        - blockless-at-rules
        - pseudo-classes

  selector-max-compound-selectors: null
  selector-no-qualifying-type: null
  'scss/function-no-unknown':
    - true
    - ignoreFunctions:
        - calculate-rem
        - strip
        - theme
        - viewport-clamp
