swagger: "2.0"
info:
  description: "This is the napari hub API for discovering napari plugins"
  version: "1.0.0"
  title: "Napari Hub API"
  contact:
    email: "team@napari-hub.org"
  license:
    name: "MIT License"
    url: "https://github.com/chanzuckerberg/napari-hub/blob/main/LICENSE"
host: "api.napari-hub.org"
tags:
- name: "plugins"
  description: "everything about plugins"
  externalDocs:
    description: "Find out more"
    url: "https://napari.org/plugins/stable/index.html"
- name: "categories"
  description: "everything about napari hub categories"
- name: "shields"
  description: "Get napari hub badge for plugin"
  externalDocs:
    description: "Find out more"
    url: "https://shields.io/"
schemes:
- "https"
paths:
  /plugins:
    get:
      tags:
      - "plugins"
      summary: "List all plugins"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Plugins"
  /plugins/index:
    get:
      tags:
      - "plugins"
      summary: "Get plugin information for index page"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Plugin"
  /plugins/excluded:
    get:
      tags:
      - "plugins"
      summary: "List excluded plugins"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ExcludedPlugin"
  /plugins/{name}:
    get:
      tags:
      - "plugins"
      summary: "Get plugin info by name"
      description: "Returns plugin for the given name"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "name of plugin to query"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Plugin"
  /categories:
    get:
      tags:
        - "categories"
      summary: "List all categories"
      description: "List all category mappings from category name to hub naming"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Categories"
  /categories/{category}:
    get:
      tags:
        - "categories"
      summary: "Get category info by name"
      description: "Returns plugin for the given name"
      produces:
        - "application/json"
      parameters:
        - name: "category"
          in: "path"
          description: "name of category to query"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
  /shields/{name}:
    get:
      tags:
      - "shields"
      summary: "Get shield by name"
      description: "Returns shield for the given name"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "name of plugin to query"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Shield"
definitions:
  Categories:
    type: object
    properties:
      <mapping>:
        $ref: "#/definitions/Category"
  Category:
    type: array
    items:
      type: object
      properties:
        dimension:
          type: string
        hierarchy:
          type: array
          items:
            type: string
        label:
            type: string
  Plugins:
    type: object
    properties:
      <name>:
        type: string
  Plugin:
    type: object
    properties:
      authors:
        type: array
        items:
          type: object
          required:
          - "name"
          - "email"
          properties:
            name:
              type: string
            email:
              type: string
              format: email
      citations:
        type: object
        required:
        - "APA"
        - "BibTex"
        - "RIS"
        - "citation"
        properties:
          APA:
            type: string
          BibTex:
            type: string
          RIS:
            type: string
          citation:
            type: string
      code_repository:
        type: string
      description:
        type: string
      description_content_type:
        type: string
      description_text:
        type: string
      development_status:
        type: array
        items:
          type: string
      first_released:
        type: string
      license:
        type: string
      name:
        type: string
      operating_system:
        type: array
        items:
          type: string
      project_site:
        type: string
      python_version:
        type: string
      release_date:
        type: string
      report_issues:
        type: string
      requirements:
        type: array
        items:
          type: string
      summary:
        type: string
      support:
        type: string
      twitter:
        type: string
      version:
        type: string
      visibility:
        type: string
  ExcludedPlugin:
    type: object
    properties:
      <name>:
        type: string
  Shield:
    type: "object"
    required:
    - "name"
    - "version"
    properties:
      color:
        type: "string"
      label:
        type: "string"
      logoSvg:
        type: "string"
      message:
        type: string
      schemaVersion:
        type: integer
      style:
        type: string
