# Workflow for running several tests for PRs and pushes to the main branch for
# napari hub client code.

name: Client Tests

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'client/**'

defaults:
  run:
    working-directory: client/

jobs:
  # Runs several tests on the client codebase to check for code style,
  # formatting, best practices, and run unit/integration tests.
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup Yarn cache
        uses: actions/cache@v2
        # use this to check for `cache-hit`:
        # (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with yarn
        run: yarn install

      - name: ${{ matrix.name }}
        run: ${{ matrix.run }}

    # Run linters and tests as matrix strategies so that they:
    #   1. Show up as separate GitHub checks.
    #   2. So we can reuse the Node.js and Yarn installation steps
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: prettier
            run: yarn lint:prettier

          - name: stylelint
            run: yarn lint:stylelint

          - name: eslint
            run: yarn lint:eslint

          - name: jest
            run: yarn test

          - name: tsc
            run: yarn type-check

  # Run E2E tests on different browsers.
  e2e:
    needs: tests
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    strategy:
      fail-fast: false
      matrix:
        # TODO Look into adding support for Edge and Webkit testing
        browser: [chromium, firefox]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup Yarn cache
        uses: actions/cache@v2
        # use this to check for `cache-hit`:
        # (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with yarn
        run: yarn install

      - name: Build for production
        run: yarn build

      - name: Start mock server on port 8081
        run: yarn start:mock-server &

      - name: Start server on port 8080
        run: yarn start &
        env:
          NODE_ENV: production

      - name: Run E2E Tests for ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
        run: yarn e2e
