# Workflow for running data-workflows tests for PRs and main branch

name: Data Workflows Tests

on:
  push:
    branches:
      - main
    paths:
      - 'data-workflows/**'
      - 'napari-hub-commons/**'
      - '.github/workflows/dataworkflow-tests.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'data-workflows/**'
      - 'napari-hub-commons/**'
      -  '.github/workflows/dataworkflow-tests.yml'

defaults:
  run:
    working-directory: data-workflows/

jobs:
  # Runs pytest for data-workflows code
  tests:
    name: Unit test with pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Cache Python environment
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        run: |
          sudo apt install libffi7
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run unit tests
        working-directory: data-workflows
        run : python -m pytest

  lints:
    name: Linting with Black
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - uses: psf/black@stable
        with:
          options: "--check --diff --color --verbose --extend-exclude '.*/tests/.*'"
          version: "~= 23.1.0"
          src: "./data-workflows"
