# Workflow for enforcing labels for on main branch PRs
# .github/workflows/enforce-labels.yml

name: Enforce Release Labels

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
    branches:
      #- main
      - joshua/enforce-release-label-workflow

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Check for labels
        uses: actions/github-script@v5
        with:
          script: |
            const checkLabels = require('./.github/check-labels.js');
            checkLabels({github, context, core});
