# Workflow for enforcing labels for on main branch PRs

# TODO: Adding this line for testing purposes. Remove before PR

name: Enforce Labels

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
    branches:
        # - main
        - joshua/enforce-release-label-workflow # TODO: Remove this before PR

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Check for labels
        run: |
          node .github/actions/check-labels.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
