# Workflow for enforcing labels for on main branch PRs

name: Enforce Release Labels

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
    branches:
      #- main
      - joshua/enforce-release-label-workflow

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '20'


      - name: Install dependencies
        run: npm install @octokit/rest @actions/github

      - name: Check for labels
        run: |
          node .github/check-labels.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


