# Workflow for running napari-hub-commons tests for PRs and main branch

name: Napari Hub Commons Tests

on:
  push:
    branches:
      - main
    paths:
      - 'napari-hub-commons/**'
      - '.github/workflows/nh-commons-tests.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'napari-hub-commons/**'
      - '.github/workflows/nh-commons-tests.yml'

defaults:
  run:
    working-directory: napari-hub-commons/

jobs:
  # Runs pytest for napari-hub-commons code
  tests:
    name: Unit test with pytest
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Cache Python environment
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install .
      - name: Run unit tests
        working-directory: napari-hub-commons
        run : python -m pytest

  lints:
    name: Linting with Black
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - uses: psf/black@stable
        with:
          options: "--check --diff --color --verbose --extend-exclude '.*/tests/.*'"
          version: "~= 23.1.0"
          src: "./napari-hub-commons"
